// src/screens/ResultsScreen.js - ENHANCED VERSION
import React from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  Alert,
  Share,
} from 'react-native';
import { globalStyles } from '../styles/globalStyles';

export default function ResultsScreen({ route, navigation }) {
  const { prediction, features } = route.params;
  
  if (!prediction) {
    return (
      <View style={globalStyles.container}>
        <Text>No prediction data</Text>
        <TouchableOpacity onPress={() => navigation.navigate('Home')}>
          <Text>Go Back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  const getRiskColor = () => {
    switch(prediction.risk_level) {
      case 'High': return '#e74c3c';
      case 'Moderate': return '#f39c12';
      case 'Low': return '#27ae60';
      default: return '#3498db';
    }
  };

  const getRiskTextColor = () => {
    switch(prediction.risk_level) {
      case 'High': return { color: '#e74c3c' };
      case 'Moderate': return { color: '#f39c12' };
      case 'Low': return { color: '#27ae60' };
      default: return { color: '#2c3e50' };
    }
  };

  const getRiskBgColor = () => {
    switch(prediction.risk_level) {
      case 'High': return { backgroundColor: '#e74c3c' };
      case 'Moderate': return { backgroundColor: '#f39c12' };
      case 'Low': return { backgroundColor: '#27ae60' };
      default: return { backgroundColor: '#3498db' };
    }
  };

  const handleShare = async () => {
    try {
      const message = `ApneaAlert Results:\n\n` +
        `Prediction: ${prediction.prediction_label}\n` +
        `Risk Level: ${prediction.risk_level}\n` +
        `Probability: ${(prediction.apnea_probability * 100).toFixed(1)}%\n` +
        `Confidence: ${(prediction.confidence * 100).toFixed(1)}%\n\n` +
        `Generated by ML model with 97.6% accuracy`;
      
      await Share.share({
        message,
        title: 'ApneaAlert Results',
      });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  const handleSave = () => {
    // We'll implement AsyncStorage later
    Alert.alert('Saved', 'Prediction saved to history (mock).');
  };

  const getRecommendations = () => {
    if (prediction.risk_level === 'High') {
      return [
        'Consult a sleep specialist immediately',
        'Consider a clinical sleep study (polysomnography)',
        'Monitor symptoms like loud snoring and daytime fatigue',
        'Avoid alcohol and sedatives before bedtime'
      ];
    } else if (prediction.risk_level === 'Moderate') {
      return [
        'Schedule a consultation with your doctor',
        'Maintain healthy sleep habits',
        'Monitor your sleep patterns',
        'Consider a follow-up test in 2-4 weeks'
      ];
    } else {
      return [
        'Maintain current healthy lifestyle',
        'Regular sleep monitoring recommended',
        'Annual health check-up advised',
        'Report any sleep-related symptoms to your doctor'
      ];
    }
  };

  const riskColor = getRiskColor();
  const riskTextStyle = getRiskTextColor();
  const riskBgStyle = getRiskBgColor();

  return (
    <ScrollView style={globalStyles.container} contentContainerStyle={globalStyles.scrollContainer}>
      <View style={globalStyles.header}>
        <Text style={globalStyles.title}>Analysis Results</Text>
      </View>

      <View style={[globalStyles.card, { borderLeftWidth: 5, borderLeftColor: riskColor }]}>
        <View style={{ alignItems: 'center', marginBottom: 25 }}>
          <Text style={[globalStyles.cardTitle, riskTextStyle]}>
            {prediction.prediction_label}
          </Text>
          <Text style={{ fontSize: 18, color: '#7f8c8d', marginTop: 5 }}>
            {(prediction.apnea_probability * 100).toFixed(1)}% probability
          </Text>
        </View>

        {/* Risk Indicator */}
        <View style={{ marginBottom: 25 }}>
          <View style={[globalStyles.riskIndicator, { height: 25 }]}>
            <View 
              style={[
                globalStyles.riskFill, 
                { 
                  width: `${Math.min(prediction.apnea_probability * 100, 100)}%`,
                  ...riskBgStyle,
                }
              ]} 
            />
          </View>
          <View style={globalStyles.riskLabels}>
            <Text style={globalStyles.riskLabel}>Low (0-30%)</Text>
            <Text style={globalStyles.riskLabel}>Moderate (31-70%)</Text>
            <Text style={globalStyles.riskLabel}>High (71-100%)</Text>
          </View>
        </View>

        {/* Stats Grid */}
        <Text style={{ fontSize: 18, fontWeight: 'bold', color: '#2c3e50', marginBottom: 15 }}>
          Prediction Details
        </Text>
        
        <View style={globalStyles.statsGrid}>
          <View style={globalStyles.statItem}>
            <Text style={globalStyles.statLabel}>Risk Level</Text>
            <Text style={[globalStyles.statValue, riskTextStyle]}>
              {prediction.risk_level}
            </Text>
          </View>
          <View style={globalStyles.statItem}>
            <Text style={globalStyles.statLabel}>Confidence</Text>
            <Text style={globalStyles.statValue}>
              {(prediction.confidence * 100).toFixed(1)}%
            </Text>
          </View>
          <View style={globalStyles.statItem}>
            <Text style={globalStyles.statLabel}>Model</Text>
            <Text style={globalStyles.statValue}>Random Forest</Text>
          </View>
          <View style={globalStyles.statItem}>
            <Text style={globalStyles.statLabel}>Accuracy</Text>
            <Text style={globalStyles.statValue}>97.6%</Text>
          </View>
        </View>

        {/* Recommendations */}
        <Text style={{ fontSize: 18, fontWeight: 'bold', color: '#2c3e50', marginTop: 20, marginBottom: 15 }}>
          Recommendations
        </Text>
        
        <View style={{ backgroundColor: '#f8f9fa', padding: 20, borderRadius: 10, marginBottom: 20 }}>
          {getRecommendations().map((rec, index) => (
            <View key={index} style={{ flexDirection: 'row', marginBottom: 10 }}>
              <Text style={{ color: riskColor, marginRight: 10, fontSize: 16 }}>•</Text>
              <Text style={{ flex: 1, color: '#2c3e50', lineHeight: 20, fontSize: 14 }}>
                {rec}
              </Text>
            </View>
          ))}
        </View>

        {/* Disclaimer */}
        <View style={{ 
          backgroundColor: '#fff3cd', 
          padding: 15, 
          borderRadius: 8,
          borderWidth: 1,
          borderColor: '#ffeaa7',
          marginBottom: 25
        }}>
          <Text style={{ color: '#856404', fontSize: 12, fontStyle: 'italic', textAlign: 'center' }}>
            ⚠️ This is a screening tool, not a medical diagnosis. Always consult with a healthcare professional for clinical evaluation and diagnosis.
          </Text>
        </View>

        {/* Action Buttons */}
        <View style={globalStyles.buttonGroup}>
          <TouchableOpacity
            style={[globalStyles.button, globalStyles.secondaryButton]}
            onPress={handleSave}
          >
            <Text style={globalStyles.buttonText}>Save to History</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={[globalStyles.button, globalStyles.secondaryButton]}
            onPress={handleShare}
          >
            <Text style={globalStyles.buttonText}>Share Results</Text>
          </TouchableOpacity>
        </View>

        <TouchableOpacity
          style={[globalStyles.button, globalStyles.primaryButton, { marginTop: 10 }]}
          onPress={() => navigation.navigate('Home')}
        >
          <Text style={globalStyles.buttonText}>New Analysis</Text>
        </TouchableOpacity>
      </View>

      <View style={globalStyles.footer}>
        <Text style={globalStyles.footerText}>
          Results generated by ML model trained on PhysioNet data
        </Text>
      </View>
    </ScrollView>
  );
}