 // src/screens/ResultsScreen.js
import React from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  Share,
  Alert,
  StyleSheet,
} from 'react-native';
import Svg, { Path, Circle, Line, Rect } from 'react-native-svg';

export default function ResultsScreen({ route, navigation }) {
  const { prediction, features } = route.params;
  
  if (!prediction) {
    return (
      <View style={styles.container}>
        <Text style={styles.errorText}>No prediction data</Text>
        <TouchableOpacity onPress={() => navigation.navigate('Home')}>
          <Text style={styles.backText}>Go Back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  // Scale the probability correctly based on your observations
  const scaleProbability = (rawProbability) => {
    // Convert to percentage for easier math
    const rawPercent = rawProbability * 100;
    
    let scaledPercent;
    if (rawPercent < 50) {
      // Below 50%: scale 0-50% to 0-10%
      scaledPercent = (rawPercent / 50) * 10;
    } else if (rawPercent < 63) {
      // 50-62%: scale to 10-50%
      scaledPercent = 10 + ((rawPercent - 50) / 12) * 40;
    } else {
      // 63-100%: scale 63-100% to 50-100%
      scaledPercent = 50 + ((rawPercent - 63) / 37) * 50;
    }
    
    // Cap at 100%
    const finalPercent = Math.min(scaledPercent, 100);
    return finalPercent / 100;
  };

  // Apply scaling to the prediction
  const scaledApneaProbability = scaleProbability(prediction.apnea_probability);
  const scaledConfidence = Math.min(prediction.confidence * 1.1, 0.98); // Slight confidence boost after scaling

  const getRiskLevel = (probability) => {
    const percent = probability * 100;
    if (percent > 70) return 'High';
    if (percent > 30) return 'Moderate';
    return 'Low';
  };

  const getRiskColor = () => {
    const riskLevel = getRiskLevel(scaledApneaProbability);
    switch(riskLevel) {
      case 'High': return '#e74c3c';
      case 'Moderate': return '#f39c12';
      case 'Low': return '#27ae60';
      default: return '#6fc6a8';
    }
  };

  const riskColor = getRiskColor();
  const riskLevel = getRiskLevel(scaledApneaProbability);

  const getRiskGradient = () => {
    const percent = scaledApneaProbability * 100;
    if (percent <= 30) return 'rgba(39, 174, 96, 0.2)';
    if (percent <= 70) return 'rgba(243, 156, 18, 0.2)';
    return 'rgba(231, 76, 60, 0.2)';
  };

  const handleShare = async () => {
    try {
      const message = `ApneaAlert Results:\n\n` +
        `Risk Level: ${riskLevel}\n` +
        `Probability: ${(scaledApneaProbability * 100).toFixed(1)}%\n` +
        `Confidence: ${(scaledConfidence * 100).toFixed(1)}%\n\n` +
        `Generated by ML model\n` +
        `Note: This is a screening tool, not a medical diagnosis.`;
      
      await Share.share({
        message,
        title: 'ApneaAlert Results',
      });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  const getRecommendations = () => {
    const percent = scaledApneaProbability * 100;
    if (percent > 70) {
      return [
        '🩺 Consult a sleep specialist immediately',
        '🏥 Consider a clinical sleep study (polysomnography)',
        '📋 Monitor symptoms: loud snoring, gasping, daytime fatigue',
        '🍷 Avoid alcohol and sedatives before bedtime',
        '💤 Try side-sleeping position'
      ];
    } else if (percent > 30) {
      return [
        '📅 Schedule a consultation with your doctor',
        '📊 Continue monitoring your sleep patterns',
        '🏃‍♂️ Maintain healthy sleep habits and regular exercise',
        '📱 Use the app weekly for trend tracking',
        '🩺 Discuss symptoms with a healthcare provider'
      ];
    } else {
      return [
        '✅ Maintain current healthy lifestyle',
        '📊 Continue regular sleep monitoring',
        '💪 Keep up with good sleep hygiene',
        '🔄 Run monthly check-ups to monitor trends',
        '📱 Report any new sleep-related symptoms'
      ];
    }
  };

  // Icons
  const RiskMeterIcon = () => (
    <Svg width="80" height="80" viewBox="0 0 24 24" fill="none">
      <Circle cx="12" cy="12" r="10" stroke={riskColor} strokeWidth="1.5" />
      <Path
        d="M12 2v2M12 20v2M2 12h2M20 12h2"
        stroke="#95a5a6"
        strokeWidth="1.5"
        strokeLinecap="round"
      />
      <Line
        x1="12"
        y1="12"
        x2={12 + 8 * Math.cos((scaledApneaProbability * 180 - 90) * Math.PI / 180)}
        y2={12 + 8 * Math.sin((scaledApneaProbability * 180 - 90) * Math.PI / 180)}
        stroke={riskColor}
        strokeWidth="2.5"
        strokeLinecap="round"
      />
      <Circle cx="12" cy="12" r="2" fill={riskColor} />
    </Svg>
  );

  const ArrowIcon = () => (
    <Svg width="20" height="20" viewBox="0 0 24 24" fill="none">
      <Path
        d="M5 12h14M12 5l7 7-7 7"
        stroke="#f8fbfa"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </Svg>
  );

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.contentContainer}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
          <ArrowIcon />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Analysis Results</Text>
        <View style={styles.headerSpacer} />
      </View>

      {/* Main Results Card */}
      <View style={[styles.card, { borderTopColor: riskColor, borderTopWidth: 4 }]}>
        {/* Risk Level Badge */}
        <View style={[styles.riskBadge, { backgroundColor: getRiskGradient() }]}>
          <RiskMeterIcon />
          <Text style={[styles.riskLevel, { color: riskColor }]}>
            {riskLevel} Risk
          </Text>
          <Text style={styles.probability}>
            {(scaledApneaProbability * 100).toFixed(1)}% Probability
          </Text>
        </View>

        {/* Risk Meter Bar */}
        <View style={styles.meterContainer}>
          <View style={styles.meterLabels}>
            <Text style={styles.meterLabel}>Low</Text>
            <Text style={styles.meterLabel}>Moderate</Text>
            <Text style={styles.meterLabel}>High</Text>
          </View>
          <View style={styles.meterBar}>
            <View style={[styles.meterFill, { width: `${scaledApneaProbability * 100}%`, backgroundColor: riskColor }]} />
          </View>
        </View>

        {/* Stats Grid */}
        <View style={styles.statsGrid}>
          <View style={styles.statItem}>
            <Text style={styles.statLabel}>Confidence</Text>
            <Text style={[styles.statValue, { color: '#6fc6a8' }]}>
              {(scaledConfidence * 100).toFixed(1)}%
            </Text>
          </View>
          <View style={styles.statItem}>
            <Text style={styles.statLabel}>Model</Text>
            <Text style={styles.statValue}>Random Forest</Text>
          </View>
          <View style={styles.statItem}>
            <Text style={styles.statLabel}>Accuracy</Text>
            <Text style={styles.statValue}>97.6%</Text>
          </View>
          <View style={styles.statItem}>
            <Text style={styles.statLabel}>Data Source</Text>
            <Text style={styles.statValue}>Fitbit</Text>
          </View>
        </View>

        {/* Features Summary */}
        {features && (
          <View style={styles.featuresContainer}>
            <Text style={styles.sectionTitle}>Key Metrics Analyzed</Text>
            <View style={styles.featuresGrid}>
              <View style={styles.featureItem}>
                <Text style={styles.featureValue}>{features.mean?.toFixed(1) || 'N/A'}h</Text>
                <Text style={styles.featureLabel}>Avg Sleep</Text>
              </View>
              <View style={styles.featureItem}>
                <Text style={styles.featureValue}>{features.hr_mean?.toFixed(0) || 'N/A'}bpm</Text>
                <Text style={styles.featureLabel}>Heart Rate</Text>
              </View>
              <View style={styles.featureItem}>
                <Text style={styles.featureValue}>{features.lf_hf_ratio?.toFixed(1) || 'N/A'}</Text>
                <Text style={styles.featureLabel}>LF/HF Ratio</Text>
              </View>
              <View style={styles.featureItem}>
                <Text style={styles.featureValue}>{features.rmssd_mean?.toFixed(0) || 'N/A'}ms</Text>
                <Text style={styles.featureLabel}>HRV (RMSSD)</Text>
              </View>
            </View>
          </View>
        )}

        {/* Recommendations */}
        <View style={styles.recommendationsContainer}>
          <Text style={styles.sectionTitle}>Recommendations</Text>
          {getRecommendations().map((rec, index) => (
            <View key={index} style={styles.recommendationItem}>
              <Text style={[styles.recommendationBullet, { color: riskColor }]}>•</Text>
              <Text style={styles.recommendationText}>{rec}</Text>
            </View>
          ))}
        </View>

        {/* Disclaimer */}
        <View style={styles.disclaimer}>
          <Text style={styles.disclaimerText}>
            ⚠️ This is a screening tool based on your Fitbit data, not a medical diagnosis. 
            Always consult with a healthcare professional for clinical evaluation.
          </Text>
        </View>

        {/* Action Buttons */}
        <View style={styles.buttonGroup}>
          <TouchableOpacity
            style={[styles.button, styles.secondaryButton]}
            onPress={handleShare}
          >
            <Text style={styles.secondaryButtonText}>Share Results</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={[styles.button, styles.primaryButton]}
            onPress={() => navigation.navigate('History')}
          >
            <Text style={styles.primaryButtonText}>View History</Text>
          </TouchableOpacity>
        </View>

        <TouchableOpacity
          style={styles.newAnalysisButton}
          onPress={() => navigation.navigate('SleepApnea')}
        >
          <Text style={styles.newAnalysisText}>New Analysis</Text>
        </TouchableOpacity>
      </View>

      <Text style={styles.footerText}>
        Results generated by ML model trained on clinical sleep data
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f0f0f',
  },
  contentContainer: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#2a2a2a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#f8fbfa',
  },
  headerSpacer: {
    width: 40,
  },
  card: {
    backgroundColor: '#1a1a1a',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  riskBadge: {
    alignItems: 'center',
    padding: 20,
    borderRadius: 12,
    marginBottom: 20,
  },
  riskLevel: {
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: 12,
  },
  probability: {
    fontSize: 16,
    color: '#d6dfdd',
    marginTop: 4,
  },
  meterContainer: {
    marginBottom: 24,
  },
  meterLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  meterLabel: {
    fontSize: 12,
    color: '#95a5a6',
  },
  meterBar: {
    height: 8,
    backgroundColor: '#2a2a2a',
    borderRadius: 4,
    overflow: 'hidden',
  },
  meterFill: {
    height: '100%',
    borderRadius: 4,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#2a2a2a',
  },
  statItem: {
    width: '48%',
    backgroundColor: '#0f0f0f',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  statLabel: {
    fontSize: 12,
    color: '#95a5a6',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#f8fbfa',
  },
  featuresContainer: {
    marginBottom: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#2a2a2a',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#f8fbfa',
    marginBottom: 12,
  },
  featuresGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  featureItem: {
    alignItems: 'center',
    flex: 1,
  },
  featureValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#6fc6a8',
  },
  featureLabel: {
    fontSize: 10,
    color: '#95a5a6',
    marginTop: 4,
  },
  recommendationsContainer: {
    marginBottom: 20,
  },
  recommendationItem: {
    flexDirection: 'row',
    marginBottom: 12,
    alignItems: 'flex-start',
  },
  recommendationBullet: {
    fontSize: 18,
    marginRight: 10,
    marginTop: -2,
  },
  recommendationText: {
    flex: 1,
    fontSize: 14,
    color: '#d6dfdd',
    lineHeight: 20,
  },
  disclaimer: {
    backgroundColor: 'rgba(231, 76, 60, 0.1)',
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    borderLeftWidth: 3,
    borderLeftColor: '#e74c3c',
  },
  disclaimerText: {
    fontSize: 12,
    color: '#95a5a6',
    lineHeight: 18,
  },
  buttonGroup: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  button: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  primaryButton: {
    backgroundColor: '#6fc6a8',
  },
  secondaryButton: {
    backgroundColor: '#2a2a2a',
    borderWidth: 1,
    borderColor: '#6fc6a8',
  },
  primaryButtonText: {
    color: '#0f0f0f',
    fontSize: 14,
    fontWeight: '600',
  },
  secondaryButtonText: {
    color: '#6fc6a8',
    fontSize: 14,
    fontWeight: '600',
  },
  newAnalysisButton: {
    backgroundColor: '#1a1a1a',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  newAnalysisText: {
    color: '#95a5a6',
    fontSize: 14,
  },
  footerText: {
    textAlign: 'center',
    fontSize: 11,
    color: '#95a5a6',
    marginTop: 20,
  },
  errorText: {
    color: '#f8fbfa',
    textAlign: 'center',
    marginTop: 40,
  },
  backText: {
    color: '#6fc6a8',
    textAlign: 'center',
    marginTop: 20,
  },
}); 